Controllers/AppointmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QueenBeautyBar.Data;

namespace QueenBeautyBar.Controllers
{
    public class AppointmentsController : Controller
    {
        dbsQueenzBeautyBarContext _context = new dbsQueenzBeautyBarContext();

        
        // GET: Appointments
        public async Task<IActionResult> Index()
        {
            return View(await _context.Appointments.ToListAsync());
        }

        // GET: Appointments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appointments = await _context.Appointments
                .FirstOrDefaultAsync(m => m.AppointmnetId == id);
            if (appointments == null)
            {
                return NotFound();
            }

            return View(appointments);
        }

        // GET: Appointments/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Appointments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AppointmnetId,Date,ServiceOption,Name,MobileNo,Email")] Appointments appointments)
        {
            if (ModelState.IsValid)
            {
                _context.Add(appointments);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(appointments);
        }

        // GET: Appointments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appointments = await _context.Appointments.FindAsync(id);
            if (appointments == null)
            {
                return NotFound();
            }
            return View(appointments);
        }

        // POST: Appointments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AppointmnetId,Date,ServiceOption,Name,MobileNo,Email")] Appointments appointments)
        {
            if (id != appointments.AppointmnetId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(appointments);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AppointmentsExists(appointments.AppointmnetId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(appointments);
        }

        // GET: Appointments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appointments = await _context.Appointments
                .FirstOrDefaultAsync(m => m.AppointmnetId == id);
            if (appointments == null)
            {
                return NotFound();
            }

            return View(appointments);
        }

        // POST: Appointments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var appointments = await _context.Appointments.FindAsync(id);
            _context.Appointments.Remove(appointments);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AppointmentsExists(int id)
        {
            return _context.Appointments.Any(e => e.AppointmnetId == id);
        }
    }
}

Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QueenBeautyBar.Data;

namespace QueenBeautyBar.Controllers
{
    public class UsersController : Controller
    {
        dbsQueenzBeautyBarContext _context = new dbsQueenzBeautyBarContext();
        // GET: Users
        public async Task<IActionResult> Index()
        {
            var dbsQueenzBeautyBarContext = _context.Users.Include(u => u.Appointmnet).Include(u => u.Gender).Include(u => u.Race).Include(u => u.Role);
            return View(await dbsQueenzBeautyBarContext.ToListAsync());
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var users = await _context.Users
                .Include(u => u.Appointmnet)
                .Include(u => u.Gender)
                .Include(u => u.Race)
                .Include(u => u.Role)
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (users == null)
            {
                return NotFound();
            }

            return View(users);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            ViewData["AppointmnetId"] = new SelectList(_context.Appointments, "AppointmnetId", "Email");
            ViewData["GenderId"] = new SelectList(_context.Gender, "GenderId", "GenderDecription");
            ViewData["RaceId"] = new SelectList(_context.Race, "RaceId", "RaceDescription");
            ViewData["RoleId"] = new SelectList(_context.Role, "RoleId", "RoleDescription");
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserId,RoleId,AppointmnetId,UsersToken,Loginname,Password,GenderId,RaceId,Firstname,Lastname,EmailAddress,MobileNo,PhysicalAddress,LastModifiedDate,CreateDate")] Users users)
        {
            if (ModelState.IsValid)
            {
                _context.Add(users);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AppointmnetId"] = new SelectList(_context.Appointments, "AppointmnetId", "Email", users.AppointmnetId);
            ViewData["GenderId"] = new SelectList(_context.Gender, "GenderId", "GenderDecription", users.GenderId);
            ViewData["RaceId"] = new SelectList(_context.Race, "RaceId", "RaceDescription", users.RaceId);
            ViewData["RoleId"] = new SelectList(_context.Role, "RoleId", "RoleDescription", users.RoleId);
            return View(users);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var users = await _context.Users.FindAsync(id);
            if (users == null)
            {
                return NotFound();
            }
            ViewData["AppointmnetId"] = new SelectList(_context.Appointments, "AppointmnetId", "Email", users.AppointmnetId);
            ViewData["GenderId"] = new SelectList(_context.Gender, "GenderId", "GenderDecription", users.GenderId);
            ViewData["RaceId"] = new SelectList(_context.Race, "RaceId", "RaceDescription", users.RaceId);
            ViewData["RoleId"] = new SelectList(_context.Role, "RoleId", "RoleDescription", users.RoleId);
            return View(users);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UserId,RoleId,AppointmnetId,UsersToken,Loginname,Password,GenderId,RaceId,Firstname,Lastname,EmailAddress,MobileNo,PhysicalAddress,LastModifiedDate,CreateDate")] Users users)
        {
            if (id != users.UserId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(users);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsersExists(users.UserId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AppointmnetId"] = new SelectList(_context.Appointments, "AppointmnetId", "Email", users.AppointmnetId);
            ViewData["GenderId"] = new SelectList(_context.Gender, "GenderId", "GenderDecription", users.GenderId);
            ViewData["RaceId"] = new SelectList(_context.Race, "RaceId", "RaceDescription", users.RaceId);
            ViewData["RoleId"] = new SelectList(_context.Role, "RoleId", "RoleDescription", users.RoleId);
            return View(users);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var users = await _context.Users
                .Include(u => u.Appointmnet)
                .Include(u => u.Gender)
                .Include(u => u.Race)
                .Include(u => u.Role)
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (users == null)
            {
                return NotFound();
            }

            return View(users);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var users = await _context.Users.FindAsync(id);
            _context.Users.Remove(users);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UsersExists(int id)
        {
            return _context.Users.Any(e => e.UserId == id);
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor sessionAccessor;
@{
    int roleID = 0;             //  assume 0 in case of guest (before users has logged in)

    if (Convert.ToInt32(sessionAccessor.HttpContext.Session.GetString("roleID")) > 0)
    {
        roleID = Convert.ToInt32(sessionAccessor.HttpContext.Session.GetString("roleID"));
    }
}



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>@ViewData["Title"] | Queenz Beauty Bar </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" href="~/css/gallery.css" />
    <link rel="stylesheet" href="~/css/slick.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/quick-hacks.css" />
    <script src="https://kit.fontawesome.com/3051aeb07b.js" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/slick.js" type="text/javascript" charset="utf-8"></script>
    <link rel="stylesheet" href="~/css/carousel.css/">


    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <!-- Slick slider -->
    <link href="assets/css/slick.css" rel="stylesheet">
    <!-- Gallery Lightbox -->
    <link href="assets/css/magnific-popup.css" rel="stylesheet">
    <!-- Skills Circle CSS  -->
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/circlebars@1.0.3/dist/circle.css">

    <!-- Animation CSS -->
    <link rel="stylesheet" type="text/css" href="./assets/css/animation.css">

    <!-- Main Style -->
    <link href="style.css" rel="stylesheet">
    <script src="https://kit.fontawesome.com/3051aeb07b.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg
        fixed-top  navbar-dark" style="background-color:#fff;">
            <a class="navbar-brand" href="/"><img src="~/Queenz/QueenLogo.svg"  id="logo" height="30" width="150" alt="mdb logo"> <strong>TISS</strong></a>
            <button class="navbar-toggler " type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" style="background-color:purple;">
                <span class="navbar-toggler-icon" sstyle="padding-left:20px"></span>
            </button>
            <div class="navbar-collapse collapse w-40 order-3 dual-collapse2 a" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto ">
                    <li class="nav-item active" id="a">
                        <a id="a" class="nav-link  text-dark" asp-area="" asp-controller="Home" asp-action="Index"><strong>HOME</strong></a>
                    </li>
                    <li class="nav-item" id="a">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="SALON"><strong>BEAUTY & SPA</strong></a>
                    </li>
                    <li class="nav-item" id="a">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Appointments" asp-action="Create"><strong>APPOINTMENT</strong></a>
                    </li>
                    <li class="nav-item dropdown text-dark" id="a">
                        <a class="nav-link dropdown-toggle text-dark" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><strong>QUEENZ BEAUTY BAR</strong></a>
                        <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item  text-dark  " asp-controller="Home" asp-action="About">ABOUT</a>
                            <a class="dropdown-item text-dark " asp-controller="Home" asp-action="Gallery">GALLERY</a>
                            <a class="dropdown-item  text-dark" asp-controller="Home" asp-action="Contact">CONTACT US</a>
                        </div>
                    </li>

                    @if (roleID == 2)
                    {

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-light" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><strong>SETUP</strong></a>
                            <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">


                                <a class="dropdown-item " asp-controller="Users" asp-action="Index">ACCOUNTS</a>

                                <a class="dropdown-item " asp-controller="Appointments" asp-action="Index">APPOINTMENT</a>

                            </div>
                        </li>
                    }
                    <li class="nav-item ">
                        <a class="nav-link " href="~/Login/" title="Sign In"><i class="fas fa-2x fa-user-circle" style="color:#E429FF"></i></a>
                    </li>
                </ul>
            </div>
            <br>

        </nav>
        <div class="toaster">
            <p></p>
        </div>
    </header>

    <div class="container-fullwidth">
       
        @RenderBody()

    </div>
    <footer id="mu-footer">
        <div class="mu-footer-top">
            <div class="container">
                <div class="row">
                    <div class="col-md-4">
                        <div class="mu-single-footer">
                            <h2><a class="mu-logo white" href="index.html"><span>Queenz Beauty Bar</span></a></h2>
                            <p>
                                The core of our business is that we ignite the beauty from within by first understanding your specific beauty and relaxation requirements and motivation. From a simple wash-and-go to the extensive self-love combo treatment, the Afroroots experience aims to leave you refreshed and rejuvenated.

                                We have created a space where men, women and the youth can come and reward themselves with the ever so deserved “ME-time” quality pampering whilst forgetting about everyday hustles that leave them tired and weary
                                <div class="mu-social-media">
                                    <a href="#"><i class="fa fa-facebook"></i></a>
                                    <a class="mu-twitter" href="#"><i class="fa fa-twitter"></i></a>
                                    <a class="mu-pinterest" href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                                    <a class="mu-youtube" href="#"><i class="fa fa-youtube"></i></a>
                                </div>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="mu-single-footer center">
                            <h3>Useful link</h3>
                            <ul class="mu-useful-links left-align">
                                <li><a href="#">Home</a></li>
                                <li><a href="about-us.html">About Us</a></li>
                                <li><a href="services.html">Services</a></li>
                                <!-- <li><a href="#">Careers</a></li> -->
                                <li><a href="contact.html">Contact Us</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="mu-single-footer">
                            <h3>Contact Information</h3>
                            <ul class="list-unstyled">
                                <li class="media">
                                    <span class="fa fa-home"></span>
                                    <div class="media-body">
                                        <p>
                                            59 Clinton Street, New Redruth, Alberton, Johannesburg, 1709
                                        </p>
                                    </div>
                                </li>
                                <li class="media">
                                    <span class="fa fa-phone"></span>
                                    <div class="media-body">
                                        <p>+27 (63) 602-9173</p>
                                    </div>
                                </li>
                                <li class="media">
                                    <span class="fa fa-envelope"></span>
                                    <div class="media-body">
                                        <p>info@queenbb.co.za</p>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="mu-footer-bottom">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                       
                    </div>
                </div>
            </div>
        </div>

    </footer>
    @*<footer class="navbar-dark  pt-5 pb-5" style="background-color:#8B008B">


                <div class="container">
                    <div class="row">
                        <div class="col-sm-12 col-md-4" style="color: rgba(255,255,255,0.9);">
                            <h3 style="font-family: 'Bree Serif', serif;">
                                QUEENZ BEAUTY BAR

                            </h3>
                            <p class="pt-4" style="font-family: 'Abel', sans-serif; font-size: 15px;">
        The core of our business is that we ignite the beauty from within by first understanding your specific beauty and relaxation requirements and motivation. From a simple wash-and-go to the extensive self-love combo treatment, the Afroroots experience aims to leave you refreshed and rejuvenated.

        We have created a space where men, women and the youth can come and reward themselves with the ever so deserved “ME-time” quality pampering whilst forgetting about everyday hustles that leave them tired and weary
                            </p>
                        </div>
                        <div class="col-sm-12 col-md-4" style="color: rgba(255,255,255,0.9);">
                            <h3 style="font-family: 'Bree Serif', serif;">Gauteng</h3>
                            <address class="lead pt-4">
                                <strong>Alberton</strong><br />
                                53 Second Avanue<br />
                                Alberton North<br />

                                1450
                            </address>
                        </div>
                        <div class="col-sm-12 col-md-4" style="color: rgba(255,255,255,0.9);">
                            <h3 style="font-family: 'Bree Serif', serif;">Contact Details</h3>
                            <address class="lead pt-4">
                                <strong>Email</strong><br />
                                <a style="color: rgba(255,255,255,0.9);" href="mailto:info@nikiwenono.co.za">info@nikiwenono.co.za</a><br />
                                <br />
                                <strong>Phone</strong><br />
                                +27 (0)73 945 8179<br />
                                +27 (0)71 483 4856<br />
                                <br />
                                <strong>Hours</strong><br />
                                Monday—Friday: 07:00AM–05:00PM
                            </address>
                        </div>

                    </div>
                    <hr style="border-color: rgba(255,255,255,0.9);" />
                    <div class="row">
                        <div class="col-sm-12"style="color: #FF1493"><strong>
            Copyright &copy; 2019 - QUEENZ BEAUTY BAR SALON  PTY (Ltd)
                        </div>
                    </div>
                </div>
            </footer>*@








    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>